using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Drawing ;

namespace MotionProfileMapper
{
    class Points
    {
        public List<Point> pts = new List<Point>();
        public double[] velTemplate;
        public double[] velMap; // real one
        public int[] timeMap; // not used yet (matched with velMap)

        public int maxVel;
        public double maxDist;
        public int sumMs;

        public double[] distancesBtPts; // from [index-1] to [index] on pts (generated by length(s, e) ), so first is always zero
        public double[] cumulativeDistances; // accumulation of distancesBtPts

        public Points()
        {
            maxVel = 100;
            fillDistances(); // should make a zero length array, to be filled later by write() in Path class
        }

        public float x(int idx)
        {
            return pts[idx].X;
        }
        public List<float> x()
        {
            List<float> r = new List<float>();
            foreach (Point p in pts)
            {
                r.Add(p.X);
            }
            return r;
        }
        public float y(int idx)
        {
            return pts[idx].Y;
        }
        public List<float> y()
        {
            List<float> r = new List<float>();
            foreach (Point p in pts)
            {
                r.Add(p.Y);
            }
            return r;
        }
        public List<Point> points()
        {
            return pts;
        }
        public void add(Point pt)
        {
            pts.Add(pt);
        }
        public void add(float[] x, float[] y)
        {
            for (int i = 0; i <= x.Length - 1; i++)
            {
                pts.Add(new Point((int)x[i], (int)y[i]));
            }
        }
        public void clear()
        {
            pts.Clear();
        }
        public float length() // length of the whole spline (roughly)
        {
            return (float)length(0, pts.Count() - 1);  // I think this is bad math  // just kidding
        }
        public float length(int startPt, int endPt)
        {
            float eSplineLength = 0;
            if (endPt > pts.Count() - 1)
            {
                endPt = pts.Count() - 1;
            }
            if (startPt < 0)
            {
                startPt = 0;
            }
            for (int i = startPt; i < endPt; i++)
            {
                eSplineLength = eSplineLength + (float)Math.Sqrt(Math.Pow((pts[i + 1].X - pts[i].X), 2) +
                    Math.Pow((pts[i + 1].Y - pts[i].Y), 2));
            }
            return eSplineLength;
        }
        public void fillDistances() // needs pts
        {
            maxDist = 0;
            distancesBtPts = new double[pts.Count()];
            for(int i = 0; i < pts.Count(); i++)
            {
                if(i == 0)
                {
                    distancesBtPts[i] = 0;
                }
                else
                {
                    distancesBtPts[i] = length(i-1, i);
                    if (distancesBtPts[i] > maxDist) maxDist = distancesBtPts[i];
                }
            }
        }
        public void velThjemplate(int f)
        {
            velTemplate = new double[pts.Count()];

        }

        public void fillCumulativeDist() // needs distancesBtPts
        {
            cumulativeDistances = new double[distancesBtPts.Count()];
            for(int i = 0; i < distancesBtPts.Count(); i++)
            {
                if(i == 0)
                {
                    cumulativeDistances[i] = 0;
                }
                else
                {
                    cumulativeDistances[i] = cumulativeDistances[i - 1] + distancesBtPts[i];
                }
            }
        }

        public void fillRealVel() // needs distancesBtPts
        {
            velMap = new double[pts.Count()];
            double size10 = pts.Count() / 10.0;
            for(int i = 0; i < distancesBtPts.Count(); i++)
            {
                velMap[i] = maxVel * (distancesBtPts[i] / maxDist);
                if (i < size10) velMap[i] *= (i / size10);
                if (i > (pts.Count() - size10)) velMap[i] *= ( (size10 - (i - (pts.Count() - size10) ) ) / size10);
                velMap[i] = (int)velMap[i];
            }
        }
        
    }


    class Path
    {
        public Points controlPoints = new Points();
        public Points spline = new Points();
        public Points leftTrack = new Points();
        public Points rightTrack = new Points();

        public int trackwidth = 600;
        public int resolution = 40;  // 60 is pretty good    // larger res = less points

        public void Create()
        {
            float[] xs, ys;

            int eSplineLength = (int)controlPoints.length();

            if(eSplineLength > 0)
            {
                //clear out the previous point
                spline.clear();
                rightTrack.clear();
                leftTrack.clear();

                //Create spline for center of the bot
                TestMySpline.CubicSpline.FitParametric(controlPoints.x().ToArray(), controlPoints.y().ToArray(), eSplineLength / resolution, out xs, out ys);
                spline.add(xs, ys);

                //calculate the tangent to the line for the left and right track
                for (int i = 1; i < spline.points().Count; i++)
                {
                    float x = spline.x(i) - spline.x(i - 1);
                    float y = spline.y(i) - spline.y(i - 1);

                    double z = -Math.Sqrt(x * x + y * y);
                    int my = -(int)(trackwidth / 2 / z * x);
                    int mx = (int)(trackwidth / 2 / z * y);

                    //Create track points 
                    rightTrack.add(new Point((int)(spline.x(i) + mx), (int)(spline.y(i) + my)));
                    leftTrack.add(new Point((int)(spline.x(i) - mx), (int)(spline.y(i) - my)));
                }
            }
            //write();

        }

        public void writeGen(String fileName)
        {
            leftTrack.fillDistances(); // calculate a bunch of distances, find the max distance
            rightTrack.fillDistances();
            if (leftTrack.maxDist > rightTrack.maxDist) rightTrack.maxDist = leftTrack.maxDist; // set the real max to max
            else leftTrack.maxDist = rightTrack.maxDist;

            leftTrack.fillCumulativeDist(); // find the total distance of the spline
            rightTrack.fillCumulativeDist();
            leftTrack.fillRealVel(); // make the velocity map
            rightTrack.fillRealVel();

            using (System.IO.StreamWriter writetext = new System.IO.StreamWriter(fileName))
            {
                writetext.WriteLine("package org.usfirst.frc.team3539.robot.profiles;");
                writetext.WriteLine("public class profile implements IProfile{");
                writetext.WriteLine("   public static final int kNumPoints = " + leftTrack.pts.Count() + ";");
                writetext.WriteLine("   public static double PointsL[][] = new double[][] {");
                // the L and R were made backwards I think, so in the printer stuff it's called in the reverse way
                leftTrack.sumMs = 0;
                rightTrack.sumMs = 0;

                for (int i = 0; i < leftTrack.pts.Count(); i++)
                {
                    if (i == 0)
                    {
                        writetext.WriteLine("       {0, 0, 10},");
                        leftTrack.sumMs += 10;
                    }
                    else if (i == leftTrack.pts.Count() - 1)
                    {
                        writetext.WriteLine("       {" + (int) rightTrack.cumulativeDistances[i] + ", " + rightTrack.velMap[i] + ", " + 10 + "}};");
                        leftTrack.sumMs += leftTrack.timeMap[i];
                    }
                    else
                    {
                        writetext.WriteLine("       {" + (int) rightTrack.cumulativeDistances[i] + ", " + rightTrack.velMap[i] + ", " + 10 + "},");
                        leftTrack.sumMs += leftTrack.timeMap[i];
                    }
                }
                writetext.WriteLine("");
                writetext.WriteLine("//Time for left side: " + leftTrack.sumMs + " ms, or " + (leftTrack.sumMs / 1000.0) + " s");
                writetext.WriteLine("   public static double PointsR[][] = new double[][] {");
                for (int i = 0; i < rightTrack.pts.Count(); i++)
                {
                    if (i == 0)
                    {
                        writetext.WriteLine("       {0, 0, 10},");
                        rightTrack.sumMs += 10;
                    }
                    else if (i == rightTrack.pts.Count() - 1)
                    {
                        writetext.WriteLine("       {" + (int) leftTrack.cumulativeDistances[i] + ", " + leftTrack.velMap[i] + ", " + 10 + "}};");
                        rightTrack.sumMs += rightTrack.timeMap[i];
                    }
                    else
                    {
                        writetext.WriteLine("       {" + (int) leftTrack.cumulativeDistances[i] + ", " + leftTrack.velMap[i] + ", " + 10 + "},");
                        rightTrack.sumMs += rightTrack.timeMap[i];
                    }
                }

                writetext.WriteLine("}");
                writetext.WriteLine("//Time for right side: " + rightTrack.sumMs + " ms, or " + (rightTrack.sumMs / 1000.0) + " s");
            }
        }

        public void writeCon(String fileName)
        {
            using (System.IO.StreamWriter writetext = new System.IO.StreamWriter(fileName))
            {

                for (int i = 0; i < controlPoints.pts.Count(); i++)
                {
                    writetext.WriteLine(controlPoints.x(i));
                    writetext.WriteLine(controlPoints.y(i));
                }

            }
        }
    }
    /* Trash Can // (Cameron Can)
    
    public double[] lookaheadMap;
    public double[] defVelMap; // default (not good) (bad)

    leftTrack.fillDefVel();
    rightTrack.fillDefVel();
    leftTrack.fillTime();
    rightTrack.fillTime();

    public void fillDefVel()
        {  //5000mms
            defVelMap = new double[pts.Count()];
            int size10 = pts.Count() / 10;
            int middle = pts.Count() - (2 * size10);
            double jumpSize = 5000 / size10;
            for(int i = 1; i <= size10; i++)
            {
                defVelMap[i - 1] = i * jumpSize;
            }
            for(int i = 0; i < middle; i++)
            {
                defVelMap[size10 + i] = 5000;
            }
            for(int i = 1; i <= size10; i++)
            {
                defVelMap[size10 + middle + i - 1] = (5000 - i * jumpSize);
            }
        }

    public int seqAngle(int fX, int fY, int sX, int sY, int tX, int tY)
        {
            // a^2 = b^2 + c^2 - 2(b)(c)cos(A)
            // A = arccos( (a^2-b^2-c^2) )
            //             -------------
            //               -2(b)(c)
            double a2 = Math.Pow(tX - sX, 2) + Math.Pow(tY - sY, 2);  // these aren't squared because
            double b2 = Math.Pow(tX - fX, 2) + Math.Pow(tY - fY, 2);  // they cancel with the distance formule
            double c2 = Math.Pow(sX - fX, 2) + Math.Pow(sY - fY, 2);  // square roots
            double tempA = (a2 - b2 - c2) / (-2 * Math.Sqrt(b2) * Math.Sqrt(c2));
            double angle = Math.Acos(tempA);
            return (int)angle;
        }

        public double angleFunc(int a)
        {
            if (a <= 100) return (1 - (0.005 * a)) * 5000;
            else return (0.4 * 5000);
        }

    public void fillLookahead() // needs pts
        {
            lookaheadMap = new double[pts.Count()];
            for (int i = 0; i < pts.Count(); i++)
            {
                //int test = seqAngle(pts[i].X, pts[i].Y, pts[i + 1].X, pts[i + 1].Y, pts[i + 15].X, pts[i + 15].Y);
                if (i < pts.Count() - 16) lookaheadMap[i] = angleFunc((seqAngle(pts[i].X, pts[i].Y, pts[i + 1].X, pts[i + 1].Y, pts[i + 15].X, pts[i + 15].Y)));
                else if (i < pts.Count() - 2) lookaheadMap[i] = angleFunc((seqAngle(pts[i].X, pts[i].Y, pts[i + 1].X, pts[i + 1].Y, pts[pts.Count() - 1].X, pts[pts.Count() - 1].Y)));
                else lookaheadMap[i] = 1;
                double testholderbecausethisisstupid = lookaheadMap[i];
            }
        }
    public void fillTime() // needs fillVelMap() and distancesBtPts
        {
            timeMap = new int[pts.Count()];
            for(int i = 0; i < pts.Count(); i++)
            {
                if(i == 0)
                {
                    timeMap[i] = 0;
                }
                else
                {
                    if (velMap[i] == 0)
                    {
                        timeMap[i] = 0;
                    }
                    else if(i == pts.Count()-1)
                    {
                        timeMap[i] = 0;
                    }
                    else
                    {
                        timeMap[i] = (int)( (distancesBtPts[i] / (velMap[i] * 50)) * 1000 );
                    }
                }
            }
        }
    */
}